### ISSUE TITLE
RHEL base images

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/ibmcloud-image-builder#23]
## What's the issue?

  - One of my friends asked me whether this repo will prepare RHEL images.

## Definition of Done

  - Discuss with Zack and see whether it's doable.

**Comment by zgrossbart** [comment]
Where would we get the RHEL images?  If we can get the RHEL images from a public server then that's fine.  Otherwise we can make RHEL a sample with instructions for how to get the image.

**Comment by syyang-in-cloud** [comment]
Hi @zgrossbart , thanks for the suggestion. 
RHEL requires logging into to RedHat portal, we won't work on RHEL.

Thanks,
Seung Yeop
