### ISSUE TITLE
parallel image build

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/ibmcloud-image-builder#39]
## What's the issue?

  - each image build takes time ... since it's qemu running on docker. For universal build, I removed the accelerator and only using qemu.
  - Too save time from the current sequential build; we should consider parallel building.

## Definition of Done

  - parallel building

**Comment by nqdao** [comment]
How should this parallel building be done? Do you want parallel building on Travis or developer's machine?

**Comment by syyang-in-cloud** [comment]
> How should this parallel building be done? Do you want parallel building on Travis or developer's machine?

Oh, thanks for the interest and potential help! 
I want on Travis.

**Comment by nqdao** [comment]
No problem. Just look like something I can help quickly.

Why 2 pipelines with Docker and Travis? Looks like Docker pipeline also covers testing.
