### ISSUE TITLE
correct the typos: Availalble -> Available, you -> your

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/ibmcloud-image-builder#41]
## What's the issue?

  - There are typos in README.md

## Definition of Done

  - correct the typos: Availalble -> Available, you -> your

**Comment by kalyani489** [comment]
I'll provide, thank you

**Comment by syyang-in-cloud** [comment]
Thanks!

**Comment by syyang-in-cloud** [comment]
The PR was merged.
