### ISSUE TITLE
tfenv and tfswitch

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/ibmcloud-image-builder#62]
## Definition of Done

  - tfenv and tfswich in the Ubuntu docker file.
  -

**Comment by syyang-in-cloud** [comment]
decided to use `tfenv` instead of `tfswitch`.

**Comment by syyang-in-cloud** [comment]
PR was merged.

**Comment by kvendingoldo** [comment]
@syyang-in-cloud btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
